const TOOLS = [
  {
    id: 1,
    name: "ChatGPT",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    description: "The world's most popular AI chatbot for writing, coding, research, and conversation.",
    fullDescription: "ChatGPT by OpenAI is a large language model that can help you write, debug code, answer questions, summarise documents, and much more. It supports GPT-4o with vision, voice, and browsing capabilities.",
    category: "writing",
    usecases: ["write", "code", "research"],
    rating: 4.8,
    pricing: "Freemium",
    features: ["Natural conversation", "Code generation", "Image understanding", "Web browsing", "Plugin support"],
    url: "https://chat.openai.com",
    popular: true
  },
  {
    id: 2,
    name: "Midjourney",
    logo: "https://www.google.com/s2/favicons?domain=midjourney.com&sz=128",
    description: "Generate stunning, photorealistic AI images from text prompts.",
    fullDescription: "Midjourney is a generative AI image tool that creates highly detailed and artistic images from natural language descriptions. Widely used by designers, artists, and marketers.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.7,
    pricing: "Paid",
    features: ["Photorealistic images", "Artistic styles", "High resolution output", "Style consistency", "Community gallery"],
    url: "https://www.midjourney.com",
    popular: true
  },
  {
    id: 3,
    name: "GitHub Copilot",
    logo: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    description: "AI-powered coding assistant that suggests code as you type.",
    fullDescription: "GitHub Copilot is trained on billions of lines of code and integrates directly into VS Code, JetBrains, and other editors. It autocompletes functions, writes tests, and explains code.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.6,
    pricing: "Paid",
    features: ["Code autocomplete", "Multi-language support", "Test generation", "Code explanation", "IDE integration"],
    url: "https://github.com/features/copilot",
    popular: false
  },
  {
    id: 4,
    name: "Notion AI",
    logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=128",
    description: "Smart notes and productivity with built-in AI writing assistant.",
    fullDescription: "Notion AI is embedded directly in Notion's workspace. It can write, edit, summarise, translate, and brainstorm — all within your notes and documents without switching tools.",
    category: "productivity",
    usecases: ["write", "organise"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["AI writing", "Summarisation", "Translation", "Action items", "Database management"],
    url: "https://www.notion.so/product/ai",
    popular: false
  },
  {
    id: 5,
    name: "Runway",
    logo: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128",
    description: "AI video generation and editing for creators and filmmakers.",
    fullDescription: "Runway offers text-to-video, image-to-video, video editing with AI, and green screen tools. Used by Hollywood studios and independent creators alike.",
    category: "video",
    usecases: ["create", "design"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Text to video", "Image to video", "AI background removal", "Motion brush", "Video inpainting"],
    url: "https://runwayml.com",
    popular: true
  },
  {
    id: 6,
    name: "Copy.ai",
    logo: "https://www.google.com/s2/favicons?domain=copy.ai&sz=128",
    description: "AI copywriting tool for ads, emails, blogs, and social media.",
    fullDescription: "Copy.ai helps marketers and writers generate high-converting copy in seconds. It supports 90+ languages and has templates for every marketing use case.",
    category: "marketing",
    usecases: ["write", "market"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["90+ languages", "Marketing templates", "Blog post generator", "Ad copy", "Email sequences"],
    url: "https://www.copy.ai",
    popular: false
  },
  {
    id: 7,
    name: "Cursor",
    logo: "https://www.google.com/s2/favicons?domain=cursor.com&sz=128",
    description: "AI-first code editor built on VS Code with deep codebase understanding.",
    fullDescription: "Cursor is a fork of VS Code with AI deeply integrated. It can understand your entire codebase, answer questions about it, and make multi-file edits in one go.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.8,
    pricing: "Freemium",
    features: ["Codebase chat", "Multi-file edits", "Bug detection", "VS Code compatible", "GPT-4 powered"],
    url: "https://www.cursor.com",
    popular: true
  },
  {
    id: 8,
    name: "ElevenLabs",
    logo: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128",
    description: "Ultra-realistic AI voice generation and voice cloning.",
    fullDescription: "ElevenLabs creates the most natural-sounding AI voices available. It supports voice cloning, multilingual dubbing, and real-time voice synthesis for apps and content.",
    category: "productivity",
    usecases: ["create", "market"],
    rating: 4.7,
    pricing: "Freemium",
    features: ["Voice cloning", "29 languages", "Real-time synthesis", "API access", "Audiobook creation"],
    url: "https://elevenlabs.io",
    popular: false
  },
  {
    id: 9,
    name: "Perplexity AI",
    logo: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128",
    description: "AI search engine that gives cited, accurate answers instantly.",
    fullDescription: "Perplexity is an AI-powered search engine that searches the web and synthesises results into a clear answer with citations. Great for research and fact-checking.",
    category: "productivity",
    usecases: ["research", "write"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Real-time web search", "Cited sources", "Follow-up questions", "File upload", "Collections"],
    url: "https://www.perplexity.ai",
    popular: true
  },
  {
    id: 10,
    name: "DALL-E 3",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    description: "OpenAI's image generation model with precise prompt following.",
    fullDescription: "DALL-E 3 is integrated into ChatGPT and the OpenAI API. It follows prompts more accurately than previous models and excels at text-in-image generation.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Text in images", "Precise prompting", "Multiple styles", "API access", "ChatGPT integration"],
    url: "https://openai.com/dall-e-3",
    popular: false
  },
  {
    id: 11,
    name: "Jasper",
    logo: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=128",
    description: "Enterprise AI writing platform for marketing teams.",
    fullDescription: "Jasper is an AI writing assistant built for marketing teams. It learns your brand voice, integrates with your tools, and helps create consistent content at scale.",
    category: "marketing",
    usecases: ["write", "market"],
    rating: 4.3,
    pricing: "Paid",
    features: ["Brand voice", "Team collaboration", "SEO mode", "Templates", "Integrations"],
    url: "https://www.jasper.ai",
    popular: false
  },
  {
    id: 12,
    name: "Synthesia",
    logo: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=128",
    description: "Create AI videos with realistic avatars — no camera needed.",
    fullDescription: "Synthesia lets you create professional videos with AI avatars from a text script. Used for training, marketing, and internal communications by 50,000+ companies.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.4,
    pricing: "Paid",
    features: ["160 AI avatars", "130 languages", "Screen recorder", "Custom avatars", "Brand kit"],
    url: "https://www.synthesia.io",
    popular: false
  }
];
