const TOOLS = [
  {
    id: 1,
    name: "ChatGPT",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    description: "The world's most popular AI chatbot for writing, coding, research, and conversation.",
    fullDescription: "ChatGPT by OpenAI is a large language model that can help you write, debug code, answer questions, summarise documents, and much more. It supports GPT-4o with vision, voice, and browsing capabilities.",
    category: "writing",
    usecases: ["write", "code", "research"],
    rating: 4.8,
    pricing: "Freemium",
    features: ["Natural conversation", "Code generation", "Image understanding", "Web browsing", "Plugin support"],
    url: "https://chat.openai.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 2,
    name: "Midjourney",
    logo: "https://www.google.com/s2/favicons?domain=midjourney.com&sz=128",
    description: "Generate stunning, photorealistic AI images from text prompts.",
    fullDescription: "Midjourney is a generative AI image tool that creates highly detailed and artistic images from natural language descriptions. Widely used by designers, artists, and marketers.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.7,
    pricing: "Paid",
    features: ["Photorealistic images", "Artistic styles", "High resolution output", "Style consistency", "Community gallery"],
    url: "https://www.midjourney.com",
    popular: true,
    freeAlternatives: [10, 22]
  },
  {
    id: 3,
    name: "GitHub Copilot",
    logo: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    description: "AI-powered coding assistant that suggests code as you type.",
    fullDescription: "GitHub Copilot is trained on billions of lines of code and integrates directly into VS Code, JetBrains, and other editors. It autocompletes functions, writes tests, and explains code.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.6,
    pricing: "Paid",
    features: ["Code autocomplete", "Multi-language support", "Test generation", "Code explanation", "IDE integration"],
    url: "https://github.com/features/copilot",
    popular: false,
    freeAlternatives: [7, 23]
  },
  {
    id: 4,
    name: "Notion AI",
    logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=128",
    description: "Smart notes and productivity with built-in AI writing assistant.",
    fullDescription: "Notion AI is embedded directly in Notion's workspace. It can write, edit, summarise, translate, and brainstorm — all within your notes and documents without switching tools.",
    category: "productivity",
    usecases: ["write", "organise"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["AI writing", "Summarisation", "Translation", "Action items", "Database management"],
    url: "https://www.notion.so/product/ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 5,
    name: "Runway",
    logo: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128",
    description: "AI video generation and editing for creators and filmmakers.",
    fullDescription: "Runway offers text-to-video, image-to-video, video editing with AI, and green screen tools. Used by Hollywood studios and independent creators alike.",
    category: "video",
    usecases: ["create", "design"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Text to video", "Image to video", "AI background removal", "Motion brush", "Video inpainting"],
    url: "https://runwayml.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 6,
    name: "Copy.ai",
    logo: "https://www.google.com/s2/favicons?domain=copy.ai&sz=128",
    description: "AI copywriting tool for ads, emails, blogs, and social media.",
    fullDescription: "Copy.ai helps marketers and writers generate high-converting copy in seconds. It supports 90+ languages and has templates for every marketing use case.",
    category: "marketing",
    usecases: ["write", "market"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["90+ languages", "Marketing templates", "Blog post generator", "Ad copy", "Email sequences"],
    url: "https://www.copy.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 7,
    name: "Cursor",
    logo: "https://www.google.com/s2/favicons?domain=cursor.com&sz=128",
    description: "AI-first code editor built on VS Code with deep codebase understanding.",
    fullDescription: "Cursor is a fork of VS Code with AI deeply integrated. It can understand your entire codebase, answer questions about it, and make multi-file edits in one go.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.8,
    pricing: "Freemium",
    features: ["Codebase chat", "Multi-file edits", "Bug detection", "VS Code compatible", "GPT-4 powered"],
    url: "https://www.cursor.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 8,
    name: "ElevenLabs",
    logo: "https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=128",
    description: "Ultra-realistic AI voice generation and voice cloning.",
    fullDescription: "ElevenLabs creates the most natural-sounding AI voices available. It supports voice cloning, multilingual dubbing, and real-time voice synthesis for apps and content.",
    category: "productivity",
    usecases: ["create", "market"],
    rating: 4.7,
    pricing: "Freemium",
    features: ["Voice cloning", "29 languages", "Real-time synthesis", "API access", "Audiobook creation"],
    url: "https://elevenlabs.io",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 9,
    name: "Perplexity AI",
    logo: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128",
    description: "AI search engine that gives cited, accurate answers instantly.",
    fullDescription: "Perplexity is an AI-powered search engine that searches the web and synthesises results into a clear answer with citations. Great for research and fact-checking.",
    category: "productivity",
    usecases: ["research", "write"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Real-time web search", "Cited sources", "Follow-up questions", "File upload", "Collections"],
    url: "https://www.perplexity.ai",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 10,
    name: "DALL-E 3",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    description: "OpenAI's image generation model with precise prompt following.",
    fullDescription: "DALL-E 3 is integrated into ChatGPT and the OpenAI API. It follows prompts more accurately than previous models and excels at text-in-image generation.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Text in images", "Precise prompting", "Multiple styles", "API access", "ChatGPT integration"],
    url: "https://openai.com/dall-e-3",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 11,
    name: "Jasper",
    logo: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=128",
    description: "Enterprise AI writing platform for marketing teams.",
    fullDescription: "Jasper is an AI writing assistant built for marketing teams. It learns your brand voice, integrates with your tools, and helps create consistent content at scale.",
    category: "marketing",
    usecases: ["write", "market"],
    rating: 4.3,
    pricing: "Paid",
    features: ["Brand voice", "Team collaboration", "SEO mode", "Templates", "Integrations"],
    url: "https://www.jasper.ai",
    popular: false,
    freeAlternatives: [6, 1]
  },
  {
    id: 12,
    name: "Synthesia",
    logo: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=128",
    description: "Create AI videos with realistic avatars — no camera needed.",
    fullDescription: "Synthesia lets you create professional videos with AI avatars from a text script. Used for training, marketing, and internal communications by 50,000+ companies.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.4,
    pricing: "Paid",
    features: ["160 AI avatars", "130 languages", "Screen recorder", "Custom avatars", "Brand kit"],
    url: "https://www.synthesia.io",
    popular: false,
    freeAlternatives: [5]
  },
  {
    id: 13,
    name: "Claude",
    logo: "https://www.google.com/s2/favicons?domain=claude.ai&sz=128",
    description: "Anthropic's AI assistant known for thoughtful, nuanced, long-form responses.",
    fullDescription: "Claude by Anthropic is designed to be helpful, harmless, and honest. It excels at long document analysis, coding, research, and nuanced writing with a 200K token context window.",
    category: "writing",
    usecases: ["write", "research", "code"],
    rating: 4.8,
    pricing: "Freemium",
    features: ["200K context window", "Document analysis", "Code generation", "Nuanced reasoning", "Safe outputs"],
    url: "https://claude.ai",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 14,
    name: "Gemini",
    logo: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128",
    description: "Google's multimodal AI assistant integrated across Google Workspace.",
    fullDescription: "Gemini is Google's flagship AI model with multimodal capabilities — it understands text, images, audio, and video. Deeply integrated with Gmail, Docs, Sheets, and Google Search.",
    category: "productivity",
    usecases: ["write", "research", "organise"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Multimodal input", "Google Workspace integration", "Real-time search", "Image generation", "Long context"],
    url: "https://gemini.google.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 15,
    name: "Grammarly",
    logo: "https://www.google.com/s2/favicons?domain=grammarly.com&sz=128",
    description: "AI writing assistant that improves grammar, tone, and clarity in real time.",
    fullDescription: "Grammarly checks grammar, spelling, punctuation, style, and tone across any platform you write on — email, docs, social media. The premium version adds advanced rewrites and plagiarism detection.",
    category: "writing",
    usecases: ["write"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Grammar check", "Tone detection", "Plagiarism checker", "Browser extension", "Style suggestions"],
    url: "https://www.grammarly.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 16,
    name: "Canva AI",
    logo: "https://www.google.com/s2/favicons?domain=canva.com&sz=128",
    description: "AI-powered design platform with text-to-image, Magic Edit, and auto-design tools.",
    fullDescription: "Canva's AI suite includes Magic Design, Magic Edit, text-to-image generation, background removal, and AI presentations. Perfect for non-designers who need professional results fast.",
    category: "image",
    usecases: ["design", "market", "create"],
    rating: 4.7,
    pricing: "Freemium",
    features: ["Magic Design", "Text to image", "Background removal", "Presentation AI", "Brand kit"],
    url: "https://www.canva.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 17,
    name: "Otter.ai",
    logo: "https://www.google.com/s2/favicons?domain=otter.ai&sz=128",
    description: "AI meeting transcription and note-taking for Zoom, Meet, and Teams.",
    fullDescription: "Otter.ai records, transcribes, and summarises meetings in real time. It integrates with Zoom, Google Meet, and Microsoft Teams to automatically capture action items and key decisions.",
    category: "productivity",
    usecases: ["organise", "research"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["Real-time transcription", "Meeting summaries", "Action items", "Zoom integration", "Speaker identification"],
    url: "https://otter.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 18,
    name: "Lumen5",
    logo: "https://www.google.com/s2/favicons?domain=lumen5.com&sz=128",
    description: "Turn blog posts and articles into engaging social media videos automatically.",
    fullDescription: "Lumen5 uses AI to convert text content into video automatically — it picks relevant stock footage, adds captions, and formats for any social platform. Ideal for content repurposing.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.2,
    pricing: "Freemium",
    features: ["Text to video", "Stock footage library", "Auto captions", "Brand templates", "Social formats"],
    url: "https://lumen5.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 19,
    name: "Surfer SEO",
    logo: "https://www.google.com/s2/favicons?domain=surferseo.com&sz=128",
    description: "AI SEO tool that optimises content for Google rankings in real time.",
    fullDescription: "Surfer SEO analyses top-ranking pages and gives you a content score, keyword suggestions, and structure recommendations as you write. It integrates with Google Docs and WordPress.",
    category: "marketing",
    usecases: ["write", "market"],
    rating: 4.5,
    pricing: "Paid",
    features: ["Content scoring", "Keyword research", "SERP analysis", "Google Docs plugin", "Content editor"],
    url: "https://surferseo.com",
    popular: false,
    freeAlternatives: [6]
  },
  {
    id: 20,
    name: "Murf AI",
    logo: "https://www.google.com/s2/favicons?domain=murf.ai&sz=128",
    description: "Studio-quality AI voiceovers for videos, podcasts, and presentations.",
    fullDescription: "Murf AI offers 120+ natural-sounding voices across 20 languages. Used by marketers, educators, and content creators to create professional voiceovers without recording equipment.",
    category: "productivity",
    usecases: ["create", "market"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["120+ voices", "20 languages", "Voice customisation", "Video sync", "Commercial license"],
    url: "https://murf.ai",
    popular: false,
    freeAlternatives: [8]
  },
  {
    id: 21,
    name: "Writesonic",
    logo: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=128",
    description: "AI writer for blogs, ads, product descriptions, and social media content.",
    fullDescription: "Writesonic generates SEO-optimised articles, Google ads, landing pages, and social posts in seconds. It includes Chatsonic — an AI chatbot with real-time web access.",
    category: "writing",
    usecases: ["write", "market"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["Blog writer", "Ad copy", "Chatsonic chatbot", "SEO optimisation", "Paraphraser"],
    url: "https://writesonic.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 22,
    name: "Adobe Firefly",
    logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
    description: "Adobe's generative AI for images, vectors, and creative assets.",
    fullDescription: "Adobe Firefly is trained on licensed content, making it safe for commercial use. It generates images, recolours vectors, and extends photos — all inside Adobe Creative Cloud apps.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Commercial safe images", "Generative fill", "Text effects", "Vector recolour", "Creative Cloud integration"],
    url: "https://firefly.adobe.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 23,
    name: "Codeium",
    logo: "https://www.google.com/s2/favicons?domain=codeium.com&sz=128",
    description: "Free AI code completion and chat for 70+ programming languages.",
    fullDescription: "Codeium provides fast, free AI code completion for over 70 languages and 40+ editors. It includes an in-editor chat for explaining, refactoring, and generating code.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.5,
    pricing: "Free",
    features: ["70+ languages", "40+ editors", "In-editor chat", "Fast autocomplete", "Free forever"],
    url: "https://codeium.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 24,
    name: "Descript",
    logo: "https://www.google.com/s2/favicons?domain=descript.com&sz=128",
    description: "Edit audio and video by editing text — like a doc for your media.",
    fullDescription: "Descript transcribes your video or podcast, then lets you edit by deleting words from the transcript. It also includes AI voice cloning, filler word removal, and screen recording.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Text-based editing", "AI voice clone", "Filler word removal", "Screen recorder", "Podcast tools"],
    url: "https://www.descript.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 25,
    name: "Tome",
    logo: "https://www.google.com/s2/favicons?domain=tome.app&sz=128",
    description: "AI-powered presentation builder that creates full decks from a prompt.",
    fullDescription: "Tome generates complete presentation decks from a single text prompt — with slides, visuals, and layout. Great for pitches, reports, and storytelling without design skills.",
    category: "productivity",
    usecases: ["write", "create", "market"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["Prompt to deck", "AI images", "Narration", "Embed anything", "One-click export"],
    url: "https://tome.app",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 26,
    name: "Stable Diffusion",
    logo: "https://www.google.com/s2/favicons?domain=stability.ai&sz=128",
    description: "Open-source image generation model you can run locally or via API.",
    fullDescription: "Stable Diffusion is a free, open-source text-to-image model by Stability AI. Run it locally for unlimited free generations or use it via DreamStudio. Highly customisable with LoRA and fine-tuning.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.4,
    pricing: "Free",
    features: ["Open source", "Local run", "Unlimited generations", "LoRA support", "Custom fine-tuning"],
    url: "https://stability.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 27,
    name: "HeyGen",
    logo: "https://www.google.com/s2/favicons?domain=heygen.com&sz=128",
    description: "Create AI spokesperson videos with talking avatars and instant translation.",
    fullDescription: "HeyGen creates professional video content using AI avatars that lip-sync to any script. Its video translation feature can dub any video into 40+ languages while preserving the speaker's voice.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["AI avatars", "Video translation", "Voice cloning", "40+ languages", "Custom avatar creation"],
    url: "https://www.heygen.com",
    popular: true,
    freeAlternatives: [12]
  },
  {
    id: 28,
    name: "Replit AI",
    logo: "https://www.google.com/s2/favicons?domain=replit.com&sz=128",
    description: "Browser-based coding with AI that builds, runs, and deploys apps.",
    fullDescription: "Replit is a browser-based IDE with built-in AI that can generate entire apps from natural language. You can code, run, and deploy projects without any local setup.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["Browser IDE", "AI code generation", "One-click deploy", "50+ languages", "Multiplayer coding"],
    url: "https://replit.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 29,
    name: "Kling AI",
    logo: "https://www.google.com/s2/favicons?domain=klingai.com&sz=128",
    description: "High-quality text-to-video and image-to-video generation by Kuaishou.",
    fullDescription: "Kling AI is a state-of-the-art video generation model from Kuaishou that produces smooth, realistic videos up to 2 minutes long from text or image prompts.",
    category: "video",
    usecases: ["create", "design"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["2-minute video generation", "Image to video", "Realistic motion", "High resolution", "Commercial use"],
    url: "https://klingai.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 30,
    name: "Ideogram",
    logo: "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=128",
    description: "AI image generator that excels at text rendering inside images.",
    fullDescription: "Ideogram is known for its ability to generate images with accurate, readable text — something most other AI image tools struggle with. Great for posters, logos, and typography-heavy designs.",
    category: "image",
    usecases: ["design", "create"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Text in images", "Poster generation", "Logo design", "Style presets", "High accuracy"],
    url: "https://ideogram.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 31,
    name: "Suno",
    logo: "https://www.google.com/s2/favicons?domain=suno.com&sz=128",
    description: "Generate full songs with vocals, instruments, and lyrics from a text prompt.",
    fullDescription: "Suno AI creates complete, radio-quality songs from a simple text prompt — including vocals, music, and lyrics. You can specify genre, mood, and style to get exactly the music you want.",
    category: "productivity",
    usecases: ["create"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Full song generation", "Vocal synthesis", "Genre control", "Lyrics generation", "Commercial license"],
    url: "https://suno.com",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 32,
    name: "v0 by Vercel",
    logo: "https://www.google.com/s2/favicons?domain=v0.dev&sz=128",
    description: "Generate UI components and full web pages from text prompts.",
    fullDescription: "v0 by Vercel generates React and Tailwind CSS components from natural language prompts. It produces clean, production-ready code that you can copy directly into your project.",
    category: "coding",
    usecases: ["code", "build", "design"],
    rating: 4.7,
    pricing: "Freemium",
    features: ["React component generation", "Tailwind CSS", "Production-ready code", "Iterative refinement", "Vercel deploy"],
    url: "https://v0.dev",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 33,
    name: "Lovable",
    logo: "https://www.google.com/s2/favicons?domain=lovable.dev&sz=128",
    description: "Build full-stack web apps from a prompt — no coding required.",
    fullDescription: "Lovable (formerly GPT Engineer) lets anyone build a complete full-stack web application by describing it in plain English. It handles frontend, backend, and database automatically.",
    category: "coding",
    usecases: ["build", "code"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Full-stack generation", "No-code friendly", "Database included", "GitHub integration", "One-click deploy"],
    url: "https://lovable.dev",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 34,
    name: "Bolt.new",
    logo: "https://www.google.com/s2/favicons?domain=bolt.new&sz=128",
    description: "Prompt, run, edit and deploy full-stack apps in the browser.",
    fullDescription: "Bolt.new by StackBlitz lets you build and deploy full-stack applications directly in the browser using AI. It supports Node.js, React, and many popular frameworks with live preview.",
    category: "coding",
    usecases: ["build", "code"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Browser-based IDE", "Full-stack AI", "Live preview", "npm support", "One-click deploy"],
    url: "https://bolt.new",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 35,
    name: "Gamma",
    logo: "https://www.google.com/s2/favicons?domain=gamma.app&sz=128",
    description: "Create beautiful presentations, documents, and webpages with AI.",
    fullDescription: "Gamma generates polished presentations and documents from a prompt or outline. The output is a web-based deck with animations, images, and a shareable link — no PowerPoint needed.",
    category: "productivity",
    usecases: ["write", "create", "market"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["AI presentations", "Web-based output", "Smart templates", "Image generation", "Analytics"],
    url: "https://gamma.app",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 36,
    name: "Semrush AI",
    logo: "https://www.google.com/s2/favicons?domain=semrush.com&sz=128",
    description: "All-in-one AI marketing platform for SEO, content, and competitor analysis.",
    fullDescription: "Semrush combines keyword research, site audit, backlink analysis, and AI content writing in one platform. The AI Writing Assistant generates SEO-optimised content based on top-ranking pages.",
    category: "marketing",
    usecases: ["market", "write", "research"],
    rating: 4.5,
    pricing: "Paid",
    features: ["Keyword research", "Site audit", "Backlink analysis", "AI content writer", "Competitor analysis"],
    url: "https://www.semrush.com",
    popular: false,
    freeAlternatives: [19]
  },
  {
    id: 37,
    name: "DeepL",
    logo: "https://www.google.com/s2/favicons?domain=deepl.com&sz=128",
    description: "The most accurate AI translator — better than Google Translate for nuance.",
    fullDescription: "DeepL uses neural networks to provide translations that sound natural and context-aware. It supports 30+ languages and is widely considered the most accurate machine translation tool available.",
    category: "writing",
    usecases: ["write", "research"],
    rating: 4.7,
    pricing: "Freemium",
    features: ["30+ languages", "Document translation", "Tone adjustment", "Glossary support", "API access"],
    url: "https://www.deepl.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 38,
    name: "Tabnine",
    logo: "https://www.google.com/s2/favicons?domain=tabnine.com&sz=128",
    description: "AI code completion that runs locally — private and fast.",
    fullDescription: "Tabnine offers AI code completion that can run entirely on your local machine, keeping your code private. It supports all major IDEs and languages with team-learning capabilities.",
    category: "coding",
    usecases: ["code", "build"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["Local AI model", "Privacy first", "All major IDEs", "Team learning", "Full-line completion"],
    url: "https://www.tabnine.com",
    popular: false,
    freeAlternatives: [23]
  },
  {
    id: 39,
    name: "Pictory",
    logo: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=128",
    description: "Turn long-form content into short branded videos automatically.",
    fullDescription: "Pictory converts blog posts, scripts, and recordings into short, shareable videos with stock footage and captions. It automatically identifies key points and creates highlights.",
    category: "video",
    usecases: ["create", "market"],
    rating: 4.3,
    pricing: "Paid",
    features: ["Script to video", "Blog to video", "Auto captions", "Brand templates", "Stock footage"],
    url: "https://pictory.ai",
    popular: false,
    freeAlternatives: [18]
  },
  {
    id: 40,
    name: "Wordtune",
    logo: "https://www.google.com/s2/favicons?domain=wordtune.com&sz=128",
    description: "AI writing companion that rewrites and improves your sentences instantly.",
    fullDescription: "Wordtune rewrites sentences to be clearer, more concise, or more engaging — while keeping your original meaning. It also summarises articles and suggests relevant facts to include.",
    category: "writing",
    usecases: ["write"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["Sentence rewriting", "Tone adjustment", "Article summary", "Fact suggestions", "Browser extension"],
    url: "https://www.wordtune.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 41,
    name: "Beautiful.ai",
    logo: "https://www.google.com/s2/favicons?domain=beautiful.ai&sz=128",
    description: "AI presentation tool that auto-formats slides as you add content.",
    fullDescription: "Beautiful.ai uses smart slide templates that automatically adjust layout and formatting as you add content. Great for teams that want consistent, professional decks without a designer.",
    category: "productivity",
    usecases: ["create", "market"],
    rating: 4.3,
    pricing: "Paid",
    features: ["Smart templates", "Auto-layout", "Team collaboration", "Brand control", "Analytics"],
    url: "https://www.beautiful.ai",
    popular: false,
    freeAlternatives: [35, 25]
  },
  {
    id: 42,
    name: "Elicit",
    logo: "https://www.google.com/s2/favicons?domain=elicit.com&sz=128",
    description: "AI research assistant that finds and summarises academic papers.",
    fullDescription: "Elicit helps researchers find relevant papers, extract key data, and summarise findings across thousands of studies. It's built specifically for scientific and academic research workflows.",
    category: "productivity",
    usecases: ["research"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["Paper search", "Data extraction", "Literature review", "Study summaries", "Export to CSV"],
    url: "https://elicit.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 43,
    name: "Udio",
    logo: "https://www.google.com/s2/favicons?domain=udio.com&sz=128",
    description: "Create music in any genre and style from a text description.",
    fullDescription: "Udio generates high-quality music tracks in virtually any genre from text prompts. You can extend, remix, and iterate on generated songs, and download them for personal or commercial use.",
    category: "productivity",
    usecases: ["create"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["Any genre", "Song extension", "Remix mode", "Vocal generation", "Commercial license"],
    url: "https://www.udio.com",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 44,
    name: "Pika",
    logo: "https://www.google.com/s2/favicons?domain=pika.art&sz=128",
    description: "AI video generation from text and images with precise control.",
    fullDescription: "Pika creates and edits videos using AI, allowing you to animate images, modify video content, and generate new clips. Known for its Pikaffects — dramatic visual transformations.",
    category: "video",
    usecases: ["create", "design"],
    rating: 4.4,
    pricing: "Freemium",
    features: ["Text to video", "Image animation", "Pikaffects", "Lip sync", "Video modification"],
    url: "https://pika.art",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 45,
    name: "Wix AI",
    logo: "https://www.google.com/s2/favicons?domain=wix.com&sz=128",
    description: "Build a complete website from a text description in minutes.",
    fullDescription: "Wix ADI (Artificial Design Intelligence) creates a full website with pages, content, and images based on a short questionnaire. You can then customise with a drag-and-drop editor.",
    category: "productivity",
    usecases: ["build", "design", "market"],
    rating: 4.2,
    pricing: "Freemium",
    features: ["AI website builder", "Auto content", "SEO tools", "E-commerce ready", "Mobile optimised"],
    url: "https://www.wix.com/ai-website-builder",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 46,
    name: "Krisp",
    logo: "https://www.google.com/s2/favicons?domain=krisp.ai&sz=128",
    description: "AI noise cancellation that removes background noise from any call.",
    fullDescription: "Krisp uses AI to remove background noise, echo, and voices from your microphone and speaker in real time — works with any conferencing app including Zoom, Teams, and Slack.",
    category: "productivity",
    usecases: ["organise"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["Background noise removal", "Echo cancellation", "Works with all apps", "Meeting transcription", "Call summary"],
    url: "https://krisp.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 47,
    name: "Hugging Face",
    logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=128",
    description: "The GitHub of AI — host, discover, and run open-source models.",
    fullDescription: "Hugging Face is the central hub for the AI/ML community. It hosts 500,000+ models, datasets, and Spaces (demo apps). Developers use it to share, discover, and deploy open-source AI models.",
    category: "coding",
    usecases: ["code", "build", "research"],
    rating: 4.8,
    pricing: "Free",
    features: ["500K+ models", "Dataset library", "Spaces demos", "Inference API", "Transformers library"],
    url: "https://huggingface.co",
    popular: true,
    freeAlternatives: []
  },
  {
    id: 48,
    name: "Consensus",
    logo: "https://www.google.com/s2/favicons?domain=consensus.app&sz=128",
    description: "Search engine that finds scientific consensus from research papers.",
    fullDescription: "Consensus is an AI-powered research tool that searches 200 million academic papers and extracts the scientific consensus on any question. Perfect for evidence-based research and fact-checking.",
    category: "productivity",
    usecases: ["research"],
    rating: 4.5,
    pricing: "Freemium",
    features: ["200M papers", "Consensus meter", "Evidence synthesis", "Citation export", "GPT-4 summaries"],
    url: "https://consensus.app",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 49,
    name: "Grok",
    logo: "https://www.google.com/s2/favicons?domain=x.ai&sz=128",
    description: "xAI's witty, real-time AI assistant with live X (Twitter) data access.",
    fullDescription: "Grok by xAI has real-time access to X (Twitter) data, making it uniquely capable of answering questions about current events. Known for its personality and willingness to tackle edgy topics.",
    category: "writing",
    usecases: ["write", "research"],
    rating: 4.3,
    pricing: "Freemium",
    features: ["Real-time X data", "Current events", "Image generation", "Fun personality", "Deep search"],
    url: "https://x.ai",
    popular: false,
    freeAlternatives: []
  },
  {
    id: 50,
    name: "Make (Integromat)",
    logo: "https://www.google.com/s2/favicons?domain=make.com&sz=128",
    description: "Visual AI automation platform to connect apps and automate workflows.",
    fullDescription: "Make (formerly Integromat) is a no-code automation platform that connects 1,500+ apps with AI-powered workflows. Build complex automations visually without writing code.",
    category: "productivity",
    usecases: ["organise", "build", "market"],
    rating: 4.6,
    pricing: "Freemium",
    features: ["1500+ app integrations", "Visual workflow builder", "AI modules", "Error handling", "Real-time execution"],
    url: "https://www.make.com",
    popular: false,
    freeAlternatives: []
  }
];
